# Generated by Django 3.0.9 on 2020-11-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deckimagebase",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deckimagebase",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The URL for the source of this image.",
                max_length=511,
            ),
        ),
        migrations.AlterField(
            model_name="deckbase",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="deckgallica",
            name="base_url",
            field=models.URLField(max_length=511),
        ),
        migrations.AlterField(
            model_name="deckimageexternal",
            name="external_url",
            field=models.URLField(max_length=511),
        ),
        migrations.AlterField(
            model_name="deckimageiiif",
            name="base_url",
            field=models.URLField(max_length=511),
        ),
        migrations.AlterField(
            model_name="decklicense",
            name="info",
            field=models.URLField(
                help_text="A URL for more information about this licence.",
                max_length=511,
            ),
        ),
        migrations.AlterField(
            model_name="decklicense",
            name="logo",
            field=models.URLField(
                help_text="A URL for the image of the logo of this licence.",
                max_length=511,
            ),
        ),
    ]
