# Generated by Django 3.0.9 on 2020-11-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0004_auto_20201102_1538"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeckLicense",
            new_name="DeckLicence",
        ),
        migrations.RenameField(
            model_name="deckimagebase",
            old_name="license",
            new_name="licence",
        ),
        migrations.AddField(
            model_name="deckimageexternal",
            name="height",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="deckimageexternal",
            name="width",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
