# Generated by Django 3.0.9 on 2020-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0005_auto_20201102_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="deckmembership",
            name="primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this image should be conisdered the primary image for the deck.",
            ),
        ),
    ]
