# Generated by Django 3.0.9 on 2020-11-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0006_deckmembership_primary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deckmembership",
            options={"ordering": ["rank"]},
        ),
    ]
