# Generated by Django 3.0.8 on 2020-11-09 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("imagedeck", "0007_auto_20201103_0931"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckImageFiler",
            fields=[
                (
                    "deckimagebase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="imagedeck.DeckImageBase",
                    ),
                ),
                (
                    "filer_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("imagedeck.deckimagebase",),
        ),
    ]
