# Generated by Django 3.0.11 on 2020-11-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("imagedeck", "0008_deckimagefiler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deckimagefiler",
            name="filer_image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deckimagefiler",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
