# Generated by Django 3.2.6 on 2021-08-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0009_auto_20201122_2300"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckIIIF",
            fields=[
                (
                    "deckbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="imagedeck.deckbase",
                    ),
                ),
                ("manifest_url", models.URLField(max_length=511)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("imagedeck.deckbase",),
        ),
    ]
